version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    networks:
      - net
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    env_file:
      - ./notification-service/.env
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  net:
    driver: bridge
