name: Node.js CI

on: [ push, pull_request] 

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js and dependencies
        uses: ./.github/actions/install

      - name: Lint
        run: npm run lint

  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Node.js and dependencies
        uses: ./.github/actions/install

      - name: Build
        run: npm run build --if-present

      - name: Run tests
        run: npm test